api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity', '%kernel.project_dir%/src/ApiSource', '%kernel.project_dir%/src/Controller']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
